### PR TITLE
Remove SelfLink

### PR DESCRIPTION
**Pull request by dhaiducek**
I wasn't 100% sure why we were using `selfLink` here, so I've replaced it with the UID since I assumed we wanted some sort of unique identifier. Otherwise, we may need to reconstruct `selfLink` ourselves if we indeed do need it.

### CODE REVIEW

**Comment by gparvin** [comment]
The self link was originally there so the UI could provide the link in the list of related resources. 
Example: For a non compliant policy, click the "Status" and then click "View details" for any template that is Not Compliant.  The table at the bottom is the related resources table and the "View yaml" link seems to work using fields other than the selfLink... so I'm agreeing here that selfLink can be removed unless someone knows of some other use case that depends on it.

**Comment by dhaiducek** [comment]
The UI constructs a SelfLink for its own uses, so maybe even the UID isn't necessary here? (Though I suppose it helps to have some sort of identifier...I haven't really dug into the code too much beyond replacing the instances with the UID)

**Comment by dhaiducek** [comment]
@ycao56 What are your thoughts on this?

**Comment by ycao56** [comment]
I think we can remove it and see if we need to change the UI. I couldn't remember if we update the UI or not.

**Comment by ycao56** [comment]
BTW, I don't see selfLink being requested by UI anymore so we must have changed it previously due to ocp47 support
image

**Comment by dhaiducek** [comment]
Do we want to remove my replacement with UID also, or is it helpful? I think it could be a simple array of resource names--I'd have to dig into the code a little deeper to be sure.

**Comment by ycao56** [comment]
I think we should completely remove it

**Comment by dhaiducek** [comment]
Done--ready for review! If these checks pass, I'll update the branch protection rules in `release` for the updated KinD version so that the PR can merge.

**Comment by ycao56** [comment]
@dhaiducek also need to update CRD https://github.com/open-cluster-management/config-policy-controller/blob/main/deploy/crds/policy.open-cluster-management.io_configurationpolicies_crd.yaml#L152
run `operator-sdk generate k8s` and `operator-sdk generate crds`
You may have to downgrade to an older version of operator-sdk as this project was generated using `v0.17.0`

**Comment by dhaiducek** [comment]
I bumped my `operator-sdk` down to `v0.17.0`. It created a `policies.policy.open-cluster-management.io` CRD. Should that also be merged here? I'm assuming not since it wasn't there before...

**Comment by ycao56** [comment]
can you also generate v1 version and put it in https://github.com/open-cluster-management/config-policy-controller/tree/main/deploy/crds/v1?

**Comment by ycao56** [comment]
also need to update https://github.com/open-cluster-management/endpoint-component-operator/blob/master/helm-charts/policy/templates/policy.open-cluster-management.io_configurationpolicies_crd.yaml

**Pull request merged**
